### ISSUE TITLE
Move SMS notifications to background job

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/beacon#117]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Is your feature request related to a problem? Please describe.
Currently SMS notifications to project moderators are done as part of the request/response cycle when an issue is opened. This can cause delays and errors.

## Desired solution
Set up a background job for SMS notifications.

**Comment by moduler** [comment]
@CoralineAda 
I will be working on this one ;)

**Comment by modullar** [comment]
Relevant [PR](https://github.com/ContributorCovenant/beacon/pull/202/)
