### ISSUE TITLE
Email of an user can be revealed through watermark on images

### ISSUE THREAD

**Issue by localhostdotdev** [ContributorCovenant/beacon#123]
The watermark service is using an md5 hash on the viewing’s user email address.

An attacker who saw an image with the watermark could calculate what the watermark would look like on a list of known email addresses. Thus revealing the target user email address when there is a match (e.g. rainbow table with md5)

The list of target users is potentially quite small (participants of a project). It could be done in a resonable time even on larger projects.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CoralineAda** [comment]
The watermark is vestigial and isn't used anymore. I plan on deleting that code.
