### ISSUE TITLE
[FEATURE] Traffic control

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/beacon#139]
To secure Beacon against attacks from users trying to anonymize their activities, add environment variable configurations to prevent logins from Tor exit nodes and/or users behind a proxy.

## Detecting Tor exit nodes
https://security.stackexchange.com/questions/38498/detecting-tor-proxy-by-reading-request-headers

## Detecting general proxies
Check for header:  https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by noahgibbs** [comment]
I'll have a go at this.

**Comment by noahgibbs** [comment]
I'm assuming the environment variables are for (separately) something like BLOCK_LOGIN_FROM_TOR and BLOCK_LOGINS_FROM_PROXY. Let me know if that's not the API you were thinking of.

I assume for proxies we'll want to detect headers: FORWARDED, X-FORWARDED-FOR, USERAGENT_VIA, PROXY_CONNECTION, XPROXY_CONNECTION, HTTP_PC_REMOTE_ADDR and/or HTTP_CLIENT_IP are what I find online as the appropriate header list. Headers are cheap to check, so easy to check them all.

Tor isn't going to send any of those but your link above mentions the Tor-supplied exit node detector service. I'll try that, and possibly also the reverse DNS method mentioned in a different answer, which would presumably be cheap and reliably available, but less capable of detecting all exit nodes. Either of these will be more expensive to check, both for Tor (denied) logins and normal okay logins. So I'll see how expensive it seems to be, and at least think about caching.

(Potentially good idea: if somebody logs in from a "most recent" IP address, that means it's presumably *not* a Tor exit node. So we *may* already have a local cache of known-good IP addresses if we want it.)

I'm not sure if an attempted login from a Tor exit node is a "suspicious" event, like a 404 or 403 that seems to be fishing for project IDs, etc, so it would get logged. I'll note that this is unusual in that it *would* present an opportunity for attackers to add an unlimited number of suspicious event log lines without having to have a valid Beacon account - so maybe just a rate-limit-type counter for how many times it has happened, and an occasional log event of some kind periodically? I'll investigate. Would also be possible to not check for Tor/proxy or log a suspicious event until they successfully log in, though that sounds like a bad UX experience. Maybe add a warning to the login page if the env vars are set, and then only check on successful login? I'll look into it.

**Comment by CoralineAda** [comment]
All of this sounds great. I will 100% trust your judgement on the best way to do this.
