### ISSUE TITLE
[FEATURE] Move email delivery to a background job

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/beacon#144]
## Is your feature request related to a problem? Please describe.
Email is currently sent synchronously, as part of the request-response cycle.

## Desired solution
Move email delivery to a background job.

**Comment by CoralineAda** [comment]
Fast follow on #117

**Comment by modullar** [comment]
@CoralineAda 
I am working on this one.

**Comment by modullar** [comment]
Relevant [PR](https://github.com/ContributorCovenant/beacon/pull/202/)
