### ISSUE TITLE
[BUG] Github bulk import doesn't think I belong to the organization

### ISSUE THREAD

**Issue by nbudin** [ContributorCovenant/beacon#155]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
I signed up for Beacon by linking my Github account.  It did request permission to a bunch of organizations, which I granted, but when I created the "New England Interactive Literature" organization in Beacon (Github org name `neinteractiveliterature`) and tried to have it bulk import the projects from there, it said: "Could not import projects: you are not a member of this GitHub organization."

## Reproducting the bug

1. Sign up for Beacon using a Github account
2. Create an organization
3. Click "Import projects from Github" inside that organzation
4. You get the error message about not being a member of this Github organization (or at least I do, maybe it isn't broken in this way for others)

## Expected behavior
It should import my Github projects from the `neinteractiveliterature` organization.

## Desktop environment
 - OS: macOS 10.14.3 Mojave
 - Browser: Chrome
 - Version: 72

**Comment by CoralineAda** [comment]
@nbudin Currently the importer is looking for your linked account in the organization's public members. neinteractiveliterature has no public members. I'll think about a way that we can make this work. In the mean time you can add some projects manually?

**Comment by nbudin** [comment]
@CoralineAda Aha, that makes sense.  I've added a couple of projects to the organization manually, and will try importing some of my non-organization projects as well.

**Comment by CoralineAda** [comment]
@nbudin I just deployed a new version that should fix the issue. Please feel free to leave another comment here if it doesn't work as expected. Thanks!

**Comment by nbudin** [comment]
It works!  I got prompted to make a token, and once I did, it got all the repos.  Thanks!
