### ISSUE TITLE
[BUG] using plus syntax to register as different emails

### ISSUE THREAD

**Issue by lsmith77** [ContributorCovenant/beacon#166]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
Trying to register with “foo+respondent@example.com” fails after registering as “foo+reporter@example.com”

## Reproducting the bug

1. Go to 
https://www.coc-beacon.com/accounts/sign_up
2. Enter name, email “foo+reporter@example.com” and password
3. Submit
4. Verify email
5. Enter name, email “foo+respondent@example.com” and password
3. Submit
4. See error that email is already taken

## Expected behavior
No error message and verification email is send

## Additional context
Not sure if this is a valid use case for production but it would be convienient during testing to support this.

**Comment by lsmith77** [comment]
I guess there is some sort of parsing going on, so that accounts are actually stored as foo@example.com?

**Comment by CoralineAda** [comment]
That's correct, and that's the way it's supposed to work. :)

For security and abuse prevention, we need to make sure that all users have unique email addresses. If this creates a problem for you in testing, I can create some email aliases for you?

**Comment by lsmith77** [comment]
yeah. I was trying the lazy way :)
