### ISSUE TITLE
[FEATURE] Routing of tickets

### ISSUE THREAD

**Issue by JanWMF** [ContributorCovenant/beacon#175]
Idea: When an incident occurs and a ticket is filed by a concerned user, it might be good to explore routing options for the destination receiving and handling the case. 

Bit of functionality: Destinations could be part of the filing interface and tied to descriptions in a drop-down menu (user selection harassment in the drop-down menu classifying the case to the best of their ability -> ticket goes to x in the backend; user selecting threat to life and limb -> ticket goes to y).

Background: On 3/14/19, I discussed Beacon with a member of the product team with Wikimedia's ecosystem in mind. In Wikimedia's case, there are different possible destinations due to its volunteer-centric governance structure, including the volunteer Code of Conduct Committee administering the CoC in technical spaces, Foundation staff (Trust and Safety & Legal) taking care of issues volunteers shouldn't be confronted with, etc. 

Just capturing the idea here :)

**Comment by CoralineAda** [comment]
This strikes me as a triage issue… I can see value in allowing the reporter to indicate that an issue is urgent, but I worry that every issue would be flagged as urgent. The language for the form control here would be very important. Do you have any ideas around that?

**Comment by CoralineAda** [comment]
@JanWMF My concern here is that if we had a checkbox for example that said "This is an urgent matter that needs immediate attention" then everyone would check it all the time. Would love to hear your thoughts on this.

**Comment by JanWMF** [comment]
Thank you @CoralineAda - I think one possible way to triage is to do so along the descriptive content dimension of the issue, not its level of perceived urgency. For example, types provided in a short dropdown menu might include:

1) "threat to life and limb"
2) "harassment"
3) "incivility"
etc.

All of those types are urgent but based on the category picked by the person filing could be routed to the appropriate destination respectively. "Incivility", for example, could well be an issue for the maintainer themselves or the code of conduct committee supporting them. "Threat to life and limb" would - in Wikimedia's case - straight to professional staff instead of the community-elected volunteer code of conduct committee.

**Comment by CoralineAda** [comment]
Could they be tied to severities in the Community Impact & Consequences Guide I wonder?

Also, would they require a separate group of moderators, or would the moderators include both the volunteers and the Foundation staff? If the latter (which is easier to implement ;) ) would having an email address (not one of the moderators' email addresses) associated with the high-urgency issues be a good way of ensuring that the right people get notified?

**Comment by JanWMF** [comment]
Thank you @CoralineAda Yes, I think these are excellent ideas; it could be tied to the levels, be constituted in one group of moderators, and distinguished by functional email address :)

**Comment by CoralineAda** [comment]
Fixed in #198

**Comment by CoralineAda** [comment]
@JanWMF This is ready to go! Thanks for the good idea.
