### ISSUE TITLE
[BUG] Broken image on confirmation instructions email

### ISSUE THREAD

**Issue by carolynvs** [ContributorCovenant/beacon#176]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
When I received the confirmation instructions email, and viewed it in Outlook one of the images in the email displays as a broken image.

When I click on the image in OWA and try to view the URL it says "https://outlook.office.com/assets/beacon_logo-c89b559b2082dbe30ec4b7271fbf7043895211666a12a60f664bdc3805e5d71d.png"

## Reproducing the bug

1. Sign up for an account
2. View the confirmation email in Outlook
3. Enable images if they were automatically hidden
4. See broken image at bottom right

## Expected behavior
No broken images

## Screenshots
![Screen Shot 2019-03-20 at 9 03 26 AM](https://user-images.githubusercontent.com/1368985/54690469-7c074080-4aef-11e9-8166-23593fc34ef2.png)

Same for Outlook Web Access (OWA)
![Screen Shot 2019-03-20 at 9 08 57 AM](https://user-images.githubusercontent.com/1368985/54690648-d7d1c980-4aef-11e9-85e8-2b921a90d515.png)

## Desktop environment
 - OS: MacOS
 - Browser FireFox
 - Version 65

**Comment by CoralineAda** [comment]
I'm pretty sure that this is happening because the app is behind http auth, so a plain request for an image will be unauthorized without a username and password.

**Comment by carolynvs** [comment]
D'oh! I should have thought of that. 😊
