### ISSUE TITLE
[BUG] I can't create two accounts with email addressed that only differ after a '+'

### ISSUE THREAD

**Issue by TheTincho** [ContributorCovenant/beacon#185]
Hi,

As testing Beacon for Debian, I created one account using the `tincho+beacon-ah@tincho.org' email to simulate one member of the anti-harassment team, and now I wanted to create an account for a hypothetical reporter, but the 'tincho+beacon-reporter@tincho.org' address gets rejected, saying that "Email address must be unique."

I am not sure if this is a bug or a feature though. But in this case, it makes it more difficult to test the platform :-)

**Comment by TheTincho** [comment]
OK, not this is surely a bug from an overly restrictive email validation routine. I tried to use my spamgourment account to set up the second user, and this address got rejected as invalid: `beacon.20.qwop@dfgh.net`.

**Comment by CoralineAda** [comment]
Hi! Yes, this is working as expected, as an anti-abuse measure. You will need 100% unique email addresses. I can set up some email aliases for you on my server; send me an email and I can do that right away.

**Comment by TheTincho** [comment]
But what about the spamgourmet address? That is certainly unique, and there is no way to know that address forwards to my tincho.org address.. The MX is different. Plus, having the same MX does not mean the user part is unique in that service (imagine all the people using gmail with custom domains)

**Comment by CoralineAda** [comment]
We also block emails from "throwaway" account providers. Spamgourmet is on that list: 

https://github.com/micke/valid_email2/blob/master/config/disposable_email_domains.yml#L12284

I know that makes it annoying for testing purposes, but I feel like it's important from a safety and security perspective.
