### ISSUE TITLE
[FEATURE] Make organizations visible in the directory

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/beacon#192]
## Problem
Some organizations with thousands of projects may want centralized reporting rather than project-level reporting.

## Desired solution
Show organizations in the directory.

## Open questions 
* Will reporters know to look for the organization rather than a particular project?
* How can seat licensing work if an organization has a single, catch-all project?
* Should the org directory be separate from the project directory?

**Comment by TheTincho** [comment]
I encountered issues around this while testing for Debian. We are a single "project", but it is not aligned with a single repository, we have thousands of them. And in general, I imagine most FLOSS projects will want only a very limited number of beacon projects where incidents can be reported.
