### ISSUE TITLE
[BUG] Github account link requests too many permissions

### ISSUE THREAD

**Issue by TheTincho** [ContributorCovenant/beacon#194]
When testing the github integration, I notice beacon is requesting:

> This application will be able to read and write all user data. This includes the following:
>
>    Private email addresses
>    Private profile information
>    Followers

Which I find too broad. Plus, I don't think beacon should be changing anything in my github account.

**Comment by CoralineAda** [comment]
Thanks for pointing this out. I changed the scope from `user` (which was read/write everything) to `read:user` (which is read public data only).
