### ISSUE TITLE
[BUG] incomplete URL sanitisation

### ISSUE THREAD

**Issue by TheTincho** [ContributorCovenant/beacon#197]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

The URL sanitisation of the "relevant links" section when opening an issue seems to be insufficient. At minimum, it is not forcing absolute URLs, and results in mistakes like linking to https://www.coc-beacon.com/projects/debian_test/www.google.com (see issues 149 and 150 in the beta site)

**Comment by CoralineAda** [comment]
Fixed in #199

**Comment by TheTincho** [comment]
Thanks!

Now, while testing this I broke something. I tried creating an issue with different kind of malformed URLs and I got a 500

**Comment by CoralineAda** [comment]
Sorry about that, that error was unrelated but I just fixed it.
