### ISSUE TITLE
[BUG] Registering gives me "page not found"

### ISSUE THREAD

**Issue by michellesanver** [ContributorCovenant/beacon#205]
## Description of the bug
I tried to register using the form, and filled in the google captcha and then got redirected to https://www.coc-beacon.com/accounts where it tells me: 

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

## Reproducting the bug
1. Register an account
2. Fill in google captcha
3. See error

**Comment by CoralineAda** [comment]
@michellesanver Oh no, sorry about that! The error occurred when the new account validation failed (missing, invalid, or duplicate email, password too short, or password and password confirmation mismatch).

 I'm pushing up a fix right now. Please let me know if you run into any other problems, and sorry again!
