### ISSUE TITLE
[BUG] Possible denial-of-service in IssueInvitationsController

### ISSUE THREAD

**Issue by noahgibbs** [ContributorCovenant/beacon#223]
The SuspiciousActivityLog entries are normally only made from controllers that require login for all actions. This means that the only way for SuspiciousActivityLog entries to be made is for an app account to be compromised (or at least exploring.) And then seeing the suspicious activity is a very good thing.

There is one exception: IssueInvitationsController calls render_forbidden from enforce_permissions - this will produce a SuspiciousActivityLog. That appears to be possible to trigger for a user who is not logged in, which would mean an unlimited number of SuspiciousActivityLog entries can be created in database storage without requiring an account.

I have not reproduced this bug in production, only checked the code for issues.

**Comment by CoralineAda** [comment]
The real issue is that the IssueInvitationsController is missing its `authenticate_account!` before filter. Thanks for catching this! I'm going to review all the other controllers to see if there are any others that are missing this.

**Comment by noahgibbs** [comment]
LGTM. Yes, PR #224 fixes my issue nicely!
