### ISSUE TITLE
[BUG] Can't edit CoC consequences

### ISSUE THREAD

**Issue by DEGoodmanWilson** [ContributorCovenant/beacon#239]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
From page https://www.coc-beacon.com/organizations/{$ORG_NAME}/consequence_guide, I cannot edit existing consequences. Clicking the "edit" button makes the editable field appear, as expected, but then they dissappear, as in the attached screenshot
 

## Reproducting the bug

1. Go to https://www.coc-beacon.com/organizations/{$ORG_NAME}/consequence_guide
2. Click on 'clone', using the Beacon Defaults
3. Scroll down to 'Level 1: Correction'
4. Click on 'edit', see error

## Expected behavior
I had hoped to have editable fields, so I coud change the consequnces.

## Screenshots

Here's a screencap. Apologies that it is a little glitchy. But you can see me scroll down, hit 'edit', and the editable fields appear, then dissappear. I attempt it three times before ending the recording (which loops).

![beaconconsequencesedit](https://user-images.githubusercontent.com/521866/59198375-e16d4980-8b93-11e9-8c85-0fadfffb0b90.gif)

## Desktop environment
 - OS: macOS 10.14.5
 - Browser Firefox
 - Version 67.0.1

## Additional context
There don't seem to by any errors in the JS console as a result of clicking 'edit',  but these errors do exist when I visit the page:
```None of the "sha384" hashes in the integrity attribute match the content of the subresource.```

```The resource at “https://www.google-analytics.com/analytics.js” was blocked because content blocking is enabled.```

**Comment by CoralineAda** [comment]
I couldn't reproduce this (Firefox 67.0.1) but I suspect that since I was using a `button` control the page was reloading. I changed this to a link to see if that addresses the problem.

**Comment by CoralineAda** [comment]
(The PR is in CI, will be deployed in about 10 minutes)

**Comment by CoralineAda** [comment]
The proposed fix is pushed up, @DEGoodmanWilson will you try again when you have the chance?

**Comment by DEGoodmanWilson** [comment]
Looks good! Form behaves as expected now. Thank you! (Unsure who is responsible for closing issues here…)
