### ISSUE TITLE
[BUG] Respondent Template view page error

### ISSUE THREAD

**Issue by DEGoodmanWilson** [ContributorCovenant/beacon#240]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
The Autoresponder template page has two modes: One for viewing (at https://www.coc-beacon.com/organizations/${PROJECT_NAME}/autoresponder) and one for editing (at https://www.coc-beacon.com/organizations/${PROJECT_NAME}/autoresponder/edit).

But the Respondent Template page only has an editing page (at https://www.coc-beacon.com/organizations/${PROJECT_NAME}/respondent_template/edit). If you try to manuall navigate by removing the `/edit`, it errors.

## Reproducting the bug

1. Go to https://www.coc-beacon.com/organizations/${PROJECT_NAME}/respondent_template
2. See error

## Expected behavior
I had hoped to see a page similar to https://www.coc-beacon.com/organizations/${PROJECT_NAME}/autoresponder 

## Desktop environment
- OS: macOS 10.14.5
- Browser Firefox
- Version 67.0.1

## Additional context
It would be nice if the Links column on the right on the project landing page (https://www.coc-beacon.com/organizations/${PROJECT_NAME}) took you to the view-only page for Respondent templates, like it does for the autoresponder templates.

**Comment by CoralineAda** [comment]
Fixed!
