### ISSUE TITLE
[BUG] Event toggle for new project is out of sync after project creation error

### ISSUE THREAD

**Issue by DEGoodmanWilson** [ContributorCovenant/beacon#241]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

## Description of the bug
Sorry, this one is a bit difficult to describe concisely. I had created a project, and then a second project. The second project was an event, and I attempted to use the same URL as the first project, not realizing that they needed to be globally unique. That's fine, I was notified with an error at the top of the page that I needed to use a unique URL for my second project. But at this point, the event toggle came out of sync, as in the screencap below.

## Reproducting the bug

1. Create a Project. Use any settings, I don't think it matters.
2. Create a second Project, with the following details:
2. Use the same URL as the first project
2. Check 'this is an event'
3. Click 'Create project'
4. See error: 'this is an event' is checked, but the event details are missing. Unchecking 'this is an event' reveals the event details

## Expected behavior
I expected that the 'this is an event' box would be checked, and the event details revealed.

## Screenshots

![urlalreadytaken](https://user-images.githubusercontent.com/521866/59199954-7aea2a80-8b97-11e9-8029-32499934153e.gif)

## Desktop environment
 - OS: macOS 10.14.5
 - Browser Firefox
 - Version 67.0.1

**Comment by CoralineAda** [comment]
Fixed, thanks for the report!
