### ISSUE TITLE
[BUG] Permissions broken when co-owning an organization

### ISSUE THREAD

**Issue by AevaOnline** [ContributorCovenant/beacon#252]
## Description of the bug
As a co-owner of an organization, the permission system seems to be broken. Specifically, I can not:
- see the Project Settings page
- create new Projects within that Organization
- create new projects within other Organizations (even new ones that I create and own)
- remove myself as an owner of the Organization
- remove myself as an owner of a Project

## Reproducting the bug
- person A creates an organization X
- person A creates a project within organization X
- person B registers an account and receives an invitation to become a co-owner of X
- person B can not do the aforementioned tasks

## Expected behavior
I would expect, as a co-owner, to have all the same rights as the original owner.

Furthermore, I would expect to be able to be the primary owner of a distinct organization, and my permissions in one org do not affect my permissions in another.

## Desktop environment
 - OS: Ubuntu 18.04
 - Browser: Firefox

## Screenshots
see attached

![Screenshot from 2019-10-10 14-56-36](https://user-images.githubusercontent.com/806320/66609589-56668500-eb6e-11e9-91de-87af3651bcfd.png)

![Screenshot from 2019-10-10 14-55-33](https://user-images.githubusercontent.com/806320/66609601-5fefed00-eb6e-11e9-85b8-7bc58856e01c.png)

![Screenshot from 2019-10-10 14-56-18](https://user-images.githubusercontent.com/806320/66609609-63837400-eb6e-11e9-9672-e69f2e5751bc.png)

![Screenshot from 2019-10-10 14-56-54](https://user-images.githubusercontent.com/806320/66609617-667e6480-eb6e-11e9-816d-0ae8c6031290.png)

**Comment by CoralineAda** [comment]
Fixed in #253
