### ISSUE TITLE
Reporter can not view issue after it has been acknowledged and a SEV assigned

### ISSUE THREAD

**Issue by AevaOnline** [ContributorCovenant/beacon#254]
Walking through the flow of reporting and responding to an issue, I hit a bug! My fictitious reporter, "Spam", can no longer access their own reported issue, here
https://www.coc-beacon.com/projects/testproject/issues/f6235811-56ab-4c75-8281-1035e2afdb59

## Description of the bug
The issue page is no longer viewable by the issue reporter.

## Reproducting the bug
I haven't done a full repro, but here are the steps which I recall doing prior to this issue happening.
- Spam opens an issue
- Mod ACKs the issue
- Mod tried to assign a SEV rating, realized those weren't cloned yet from the parent org, and cloned them
- Mod assigns SEV1 to the issue
- Mod replies to the ticket using the "Reporter Talk" tab
- Spam received email notification, followed the link, and could no longer access the report. Only a blank page is shown

## Desktop environment
 - OS: Ubuntu
 - Browser: Mod is using Firefox; Spam is using chromium

**Comment by CoralineAda** [comment]
The project should not have been able to accept issues without a consequences guide. That's where the bug is.

**Comment by CoralineAda** [comment]
Fixed in #256
